In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Crecimiento del PIB (% anual)

Tasa de crecimiento anual porcentual del PIB a precios de mercado en moneda local, a precios constantes. Los agregados están expresados en dólares de los Estados Unidos a precios constantes del año 2010. El PIB es la suma del valor agregado bruto de todos los productores residentes en la economía más todo impuesto a los productos, menos todo subsidio no incluido en el valor de los productos. Se calcula sin hacer deducciones por depreciación de bienes manufacturados o por agotamiento y degradación de recursos naturales.

In [2]:
#Leo el dataset
df_cre_pbi = pd.read_excel('/Users/gaston/Downloads/Banco_Mundial_Crecimiento_del_PBI_%anual.xls', sheet_name='Data')
df_cre_pbi.head()

,Data Source,Indicadores del desarrollo mundial,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
0,Last Updated Date,2023-09-19 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.000000,1962.000000,1963.000000,1964.000000,1965.00000,...,2013.000000,2014.000000,2015.000000,2016.000000,2017.000000,2018.000000,2019.000000,2020.000000,2021.000000,2022.000000
3,Aruba,ABW,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,6.429817,-0.020479,3.543630,2.116716,5.482371,5.257855,0.635030,-18.589099,17.172509,NaN
4,NaN,AFE,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,0.254879,7.965825,5.148217,4.579328,5.34621,...,4.219599,3.994682,2.974101,2.224524,2.546973,2.513984,2.087765,-2.888681,4.334927,3.404852

In [3]:
#Borro las 2 primeras filas del df
df_cre_pbi = df_cre_pbi.iloc[2:]

# Restablezco los índices del DataFrame después de eliminar la primera fila
df_cre_pbi = df_cre_pbi.reset_index(drop=True)

# Establezco la primera fila como los nombres de las columnas
df_cre_pbi.columns = df_cre_pbi.iloc[0]

# Elimino la primera fila actual
df_cre_pbi = df_cre_pbi.iloc[1:]

# Restablezco los índices del DataFrame después de eliminar la primera fila
df_cre_pbi = df_cre_pbi.reset_index(drop=True)
df_cre_pbi.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0
0,Aruba,ABW,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,6.429817,-0.020479,3.543630,2.116716,5.482371,5.257855,0.635030,-18.589099,17.172509,NaN
1,NaN,AFE,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,0.254879,7.965825,5.148217,4.579328,5.346210,...,4.219599,3.994682,2.974101,2.224524,2.546973,2.513984,2.087765,-2.888681,4.334927,3.404852
2,Afganistán,AFG,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,5.600745,2.724543,1.451315,2.260314,2.647003,1.189228,3.911603,-2.351101,-20.700000,NaN
3,NaN,AFW,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,1.854872,3.772845,7.278612,5.410812,4.081666,...,6.109741,5.929463,2.750042,0.125435,2.313219,2.813142,3.212407,-0.927800,3.980848,3.762758
4,Angola,AGO,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.954613,4.822559,0.943572,-2.580111,-0.147150,-1.316362,-0.702273,-5.638215,1.199211,3.045403

In [4]:
# Convierto los nombres de las columnas a cadenas (strings)
df_cre_pbi.columns = df_cre_pbi.columns.astype(str)

# Eliminar ".0" de los nombres de las columnas
df_cre_pbi.columns = df_cre_pbi.columns.str.replace('.0', '')
df_cre_pbi.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Aruba,ABW,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,6.429817,-0.020479,3.543630,2.116716,5.482371,5.257855,0.635030,-18.589099,17.172509,NaN
1,NaN,AFE,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,0.254879,7.965825,5.148217,4.579328,5.346210,...,4.219599,3.994682,2.974101,2.224524,2.546973,2.513984,2.087765,-2.888681,4.334927,3.404852
2,Afganistán,AFG,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,5.600745,2.724543,1.451315,2.260314,2.647003,1.189228,3.911603,-2.351101,-20.700000,NaN
3,NaN,AFW,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,1.854872,3.772845,7.278612,5.410812,4.081666,...,6.109741,5.929463,2.750042,0.125435,2.313219,2.813142,3.212407,-0.927800,3.980848,3.762758
4,Angola,AGO,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,NaN,NaN,NaN,NaN,NaN,...,4.954613,4.822559,0.943572,-2.580111,-0.147150,-1.316362,-0.702273,-5.638215,1.199211,3.045403

In [7]:
# Filtro los países en el DataFrame (los 10 destinos más frecuentas a donde emigran los argentinos y argentina)
destinos_deseados = [
    "Argentina",
    "España",
    "Estados Unidos",
    "Paraguay",
    "Chile",
    "Italia",
    "Israel",
    "Bolivia",
    "Brasil",
    "Uruguay",
    "Canadá"
]

filtered_df = df_cre_pbi[df_cre_pbi['Country Name'].isin(destinos_deseados)]

# Reseteo los índices
filtered_df = filtered_df.reset_index(drop=True)

filtered_df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,Argentina,ARG,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,5.427843,-0.852022,-5.308197,10.130298,10.569433,...,2.405324,-2.512615,2.731160,-2.080328,2.818503,-2.617396,-2.000861,-9.943235,10.398249,5.243044
1,Bolivia,BOL,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,2.089296,5.578918,6.797626,3.956597,4.913442,...,6.796011,5.460570,4.857187,4.263921,4.195206,4.223624,2.216706,-8.737884,6.105804,3.070055
2,Brasil,BRA,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,8.600000,6.600000,0.600000,3.400000,2.400000,...,3.004823,0.503956,-3.545763,-3.275917,1.322869,1.783667,1.220778,-3.276759,4.988850,2.900531
3,Canadá,CAN,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,3.163292,7.425385,5.349546,6.642894,6.316714,...,2.329123,2.870036,0.659177,1.001394,3.039880,2.777041,1.888224,-5.074358,5.011801,3.396202
4,Chile,CHL,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,5.245272,4.026686,5.840140,2.557221,0.950273,...,3.308508,1.792649,2.151942,1.753039,1.357695,3.990029,0.743130,-6.145247,11.737431,2.440403
5,España,ESP,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,11.838674,9.953438,9.596499,5.308510,6.253135,...,-1.403342,1.395775,3.838519,3.037774,2.975761,2.284469,1.983966,-11.325438,5.519595,5.451740
6,Israel,ISR,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,11.203886,10.156117,10.695713,7.937192,9.093966,...,4.415502,3.919127,2.485826,4.521680,4.276596,4.070322,4.156138,-1.857289,8.611990,6.464668
7,Italia,ITA,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,8.207246,6.203650,5.609728,2.797702,3.268024,...,-1.841065,-0.004548,0.778304,1.293463,1.667859,0.925811,0.483198,-8.979126,6.986766,3.674683
8,Paraguay,PRY,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,6.900286,3.300259,4.710291,4.212477,6.167975,...,8.293076,5.301239,2.957152,4.268026,4.810079,3.204250,-0.401855,-0.819785,4.016737,0.075439
9,Uruguay,URY,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,2.493038,-1.574549,0.170459,2.440521,1.045604,...,4.637539,3.238791,0.370741,1.689798,1.740376,0.156000,0.744432,-6.262977,5.276559,4.921874
10,Estados Unidos,USA,Crecimiento del PIB (% anual),NY.GDP.MKTP.KD.ZG,NaN,2.300000,6.100000,4.400000,5.800000,6.400000,...,1.841875,2.287776,2.706370,1.667472,2.241921,2.945385,2.294439,-2.767803,5.945485,2.061593